[package]
name = "RayTracer"
version = "0.1.0"
authors = ["Rickard <rmarte@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
cgmath = "0.14.0"
